### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: WSGI application 'main.wsgi.application' could not be loaded; Error importing module.

### ISSUE THREAD

**Issue by mahdiashtian** [IV1T3/django-middleware-fileuploadvalidation#40]
Hi
I ran into the following problem
django.core.exceptions.ImproperlyConfigured: WSGI application 'main.wsgi.application' could not be loaded; Error importing module.
Can anyone help me?

my settings:
WSGI_APPLICATION = 'main.wsgi.application'

**Comment by mahdiashtian** [comment]
You used the old version of the middleware and the program does not work properly

**Comment by mahdiashtian** [comment]
I solved the problem
This error was because the old version of middleware was used
By override the code and updating it to the new version, the problem will be solved

**Comment by wichmannpas** [comment]
Thanks for your report. This repository contains only the bare middleware without a Django project. I suppose this issue is related to the Django project itself and not the middleware?

**Comment by wichmannpas** [comment]
> I solved the problem
> This error was because the old version of middleware was used
> By override the code and updating it to the new version, the problem will be solved

Great, thanks for the reply!

**Comment by mahdiashtian** [comment]
> > I solved the problem
> > This error was because the old version of middleware was used
> > By override the code and updating it to the new version, the problem will be solved
> 
> Great, thanks for the reply! Were any changes to the middleware itself required?

Yeah
But it doesn't seem logical
I used MiddlewareMixin and rewrote the code and the problem was solved

**Comment by mahdiashtian** [comment]
> > I solved the problem
> > This error was because the old version of middleware was used
> > By override the code and updating it to the new version, the problem will be solved
> 
> Great, thanks for the reply! Were any changes to the middleware itself required?

I improved your code and added some features
I wanted to get permission to put the code in my GitHub

**Comment by wichmannpas** [comment]
You can create a fork and send a pull request. Greatly appreciated, thanks!

**Comment by mahdiashtian** [comment]
> You can create a fork and send a pull request. Greatly appreciated, thanks!

ok

**Comment by IV1T3** [comment]
> > > I solved the problem
> > > This error was because the old version of middleware was used
> > > By override the code and updating it to the new version, the problem will be solved
> > 
> > 
> > Great, thanks for the reply! Were any changes to the middleware itself required?
> 
> I improved your code and added some features I wanted to get permission to put the code in my GitHub

Hey Mahdi! Would you mind sharing your improvements with the community? Maybe we could even get your changes merged into our upcoming new release. Highly appreciated!
